### ISSUE TITLE
$('#codefile-pre').syntax() doesn't work

### ISSUE THREAD

**Issue by tshi0912** [ioquatix/jquery-syntax#7]
Only $.syntax() worked, however with selected jquery object, it doesn't work, even through it's exampled, such as:
$('div.java').syntax({
    brush: 'java',
    layout: 'fixed', 
    tabWidth: 8,
    replace: true
});

**Comment by ioquatix** [comment]
Thanks. I will consider this issue you had when reviewing the documentation so it could be clear for new users.
