### ISSUE TITLE
Swift language support

### ISSUE THREAD

**Issue by joelmartinez** [ioquatix/jquery-syntax#9]
Are you aware of any effort to add support for the swift language?

**Comment by ioquatix** [comment]
Nope but it's a good idea. In all honestly, while I still use this code base extensively, I believe it could do with a bit of refactoring to bring it up to modern standards. Are you using it?

In any case, it's very easy to add support for a new language. If you can give me a list of keywords and other semantic elements I'd be happy to throw it together.

**Comment by ioquatix** [comment]
I may add swift support soon.

**Comment by joelmartinez** [comment]
@ioquatix awesome, great news :D please feel free to ping if you want/need anyone to help test it :)

**Comment by joelmartinez** [comment]
I'm just now realizing that I never replied to your original reply ... my apologies. You can find authoritative information about the language itself here:  
https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/TheBasics.html#//apple_ref/doc/uid/TP40014097-CH5-ID309

and here  
https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/AboutTheLanguageReference.html

**Comment by ioquatix** [comment]
Um, if you want to try it out.. that would be great. I guess support is pretty basic, and string interpolation support.. is pretty much broken, but I'll work on it a bit more.
